SETTINGS:
    # 用于按下反应任务等的 Discord 令牌，用于获取表情信息
    DISCORD_TOKEN_FOR_PARSING: ""
    # 解析用的代理。格式：username:password@ip:port
    PROXY_FOR_PARSING: ""

    # 并发线程数
    THREADS: 1

    # 任何操作的重试次数
    ATTEMPTS: 5

    # 随机顺序打乱账户
    SHUFFLE_ACCOUNTS: true

    # 账户范围。
    # 默认：[0, 0] - 所有账户
    # [3, 5] - 仅 3 4 5 账户
    # [7, 7] - 仅 7 账户
    ACCOUNTS_RANGE: [0, 0]

    # 仅在 ACCOUNTS_RANGE 为 [0, 0] 时生效
    # 使用的确切账户。
    # 默认：[] - 所有账户
    # 示例：[1, 4, 6] - 机器人将仅使用 1, 4 和 6 账户
    EXACT_ACCOUNTS_TO_USE: []

    # 重试之间的暂停
    PAUSE_BETWEEN_ATTEMPTS: [1, 2]

    # 账户之间的随机暂停时间（秒）
    RANDOM_PAUSE_BETWEEN_ACCOUNTS: [1, 2]

    # 操作之间的随机暂停时间（秒）
    RANDOM_PAUSE_BETWEEN_ACTIONS: [1, 2]

    # 每个账户开始前的随机暂停时间
    # 以确保所有账户将在不同时间启动
    RANDOM_INITIALIZATION_PAUSE: [1, 2]

    # 更改个人资料图片任务是否使用随机个人资料图片
    RANDOM_PROFILE_PICTURES: true


AI_CHATTER:
    # 机器人将发送消息的 Discord 服务器 ID
    GUILD_ID: ""

    # 机器人将发送消息的 Discord 频道 ID
    CHANNEL_ID: ""

    # 当机器人被问到某些问题时，它回答或忽略问题的概率
    ANSWER_PERCENTAGE: 50

    # 多少百分比的文本将回复其他用户的文本
    # 剩下的短信将直接发送到聊天中。
    # 如果为 0，则机器人不会回复任何人
    # 如果为 100，则机器人将仅对其他用户的短信进行回复。
    REPLY_PERCENTAGE: 50

    # 每个账户要发送的消息数量
    MESSAGES_TO_SEND_PER_ACCOUNT: [3, 5]

    # 消息之间的暂停时间
    PAUSE_BETWEEN_MESSAGES: [3, 5]

    # 从 chatgpt 获取响应后发送消息到 discord 之前的暂停时间
    PAUSE_BEFORE_MESSAGE: [1, 2]
    

MESSAGE_SENDER:
    # 机器人将发送消息的 Discord 服务器 ID
    GUILD_ID: ""

    # 机器人将发送消息的 Discord 频道 ID
    CHANNEL_ID: ""
    
    # 发送后立即删除消息
    DELETE_MESSAGE_INSTANTLY: false

    # 随机发送消息
    SEND_MESSAGES_RANDOMLY: false

    # 每个账户要发送的消息数量。每个账户将发送此数量的消息
    NUMBER_OF_MESSAGES_TO_SEND: 3

    # 消息之间的暂停时间
    PAUSE_BETWEEN_MESSAGES: [1, 5]


CHAT_GPT:
    # API 密钥列表。机器人将为每条消息随机使用一个 API 密钥。
    API_KEYS: ["sk-proj-"]
    # 要使用的 chatgpt 模型。https://platform.openai.com/docs/models
    MODEL: "gpt-4o"

    # 在某些国家/地区，您可能需要使用代理访问 chatgpt。
    # 默认情况下为空。格式：username:password@ip:port
    PROXY_FOR_CHAT_GPT: ""

DEEPSEEK:
    # API 密钥列表。机器人将为每条消息随机使用一个 API 密钥。
    API_KEYS: ["sk-"]
    # 要使用的 deepseek 模型
    MODEL: "deepseek-chat"

    # 在某些国家/地区，您可能需要使用代理访问 deepseek。
    # 默认情况下为空。格式：username:password@ip:port
    PROXY_FOR_DEEPSEEK: ""
